import os
import glob
import matplotlib.pyplot as plt
import numpy as np
from evaluate import split_text_into_sentences
from baseline import split_with_nltk

def evaluate_on_test_data(test_file):
    with open(test_file, 'r', encoding='utf-8') as f:
        raw_text = f.read()

    raw_sentences = raw_text.split('<EOS>')
    
    text_blocks = []
    current_block = ""
    
    for i, sentence in enumerate(raw_sentences):
        if i == len(raw_sentences) - 1 and not sentence.strip():
            continue
            
        sentence_with_eos = sentence + "<EOS>"
        
        if len(current_block) + len(sentence_with_eos) > 1500:
            if current_block:
                text_blocks.append(current_block)
            current_block = sentence_with_eos
        else:
            current_block += sentence_with_eos
            
    if current_block:
        text_blocks.append(current_block)

    file_name = os.path.basename(test_file)
    if file_name.startswith("it"):
        nltk_lang = "italian"
    elif file_name.startswith("en"):
        nltk_lang = "english"
    else:
        nltk_lang = "english"
        print(f"Language not recognized in {file_name}, setting english as default.\n")
    
    total_true_sentences = 0
    total_model_sentences = 0
    total_nltk_sentences = 0
    correct_model_sentences = 0
    correct_nltk_sentences = 0

    print(f"\nTesting on: {test_file}")
    print("Model in action...")

    for block in text_blocks:
        if not block.strip():
            continue

        true_sentences = [s.strip() for s in block.split('<EOS>') if s.strip()]
        total_true_sentences += len(true_sentences)
        
        #Input of the model
        clean_text = block.replace('<EOS>', '')
        
        #Sentences extraction
        model_sentences = [s.strip() for s in split_text_into_sentences(clean_text)]
        nltk_sentences = [s.strip() for s in split_with_nltk(clean_text, language=nltk_lang)]
        
        total_model_sentences += len(model_sentences)
        total_nltk_sentences += len(nltk_sentences)

        #Calculate number of correct sentences
        true_sentences_copy_model = true_sentences.copy()
        for s in model_sentences:
            if s in true_sentences_copy_model:
                correct_model_sentences += 1
                true_sentences_copy_model.remove(s)
            
        true_sentences_copy_nltk = true_sentences.copy()
        for s in nltk_sentences:
            if s in true_sentences_copy_nltk:
                correct_nltk_sentences += 1
                true_sentences_copy_nltk.remove(s)

    #Metrics for evaluation
    #Recall = TP/(TP+FN) (true positives/ALL true positives)
    #Precision = TP/(TP+FP) (true positives/ALL predicted positives)
    #F1-score = 2*(Precision*Recall)/(Precision+Recall) (harmonic mean of precision and recall)
    #TP = true positives <-> correct_<model,nltk>_sentences
    #FP = false positives <-> (total_model_sentences-correct_model_sentences)
    #FN = false negatives <-> (total_true_sentences-correct_model_sentences)

    #Metrics for modified RoBERTa
    precision_model = correct_model_sentences / total_model_sentences if total_model_sentences > 0 else 0
    recall_model = correct_model_sentences / total_true_sentences if total_true_sentences > 0 else 0
    f1_model = (2 * precision_model * recall_model) / (precision_model + recall_model) if (precision_model + recall_model) > 0 else 0

    #Metrics for NTLK
    precision_nltk = correct_nltk_sentences / total_nltk_sentences if total_nltk_sentences > 0 else 0
    recall_nltk = correct_nltk_sentences / total_true_sentences if total_true_sentences > 0 else 0
    f1_nltk = (2 * precision_nltk * recall_nltk) / (precision_nltk + recall_nltk) if (precision_nltk + recall_nltk) > 0 else 0

    print("\n" + "="*60)
    print(f" RESULTS ON TEST SET: {file_name} ".center(60, "="))
    print("="*60)
    print(f"Total sentences to find: {total_true_sentences}")
    
    print("-" * 60)
    print("XLM-RoBERTa:")
    print(f"  Sentences generated by the model: {total_model_sentences}")
    print(f"  Correct sentences:  {correct_model_sentences}")
    print(f"  Recall: {recall_model*100:.2f}%")
    print(f"  Precision:         {precision_model*100:.2f}%")
    print(f"  F1-Score:          {f1_model*100:.2f}%")
    
    print("-" * 60)
    print("NLTK:")
    print(f"  Sentences generated by NLTK:     {total_nltk_sentences}")
    print(f"  Correct sentences:  {correct_nltk_sentences}")
    print(f"  Recall: {recall_nltk*100:.2f}%")
    print(f"  Precision:         {precision_nltk*100:.2f}%")
    print(f"  F1-Score:          {f1_nltk*100:.2f}%\n")
    
    #retrurns the f1 scores and the file to plot the performances
    return f1_model, f1_nltk, file_name


if __name__ == "__main__":

    # =====================================================================
    # TEST IN CLASS. 
    # Decomment the 3 lines below and insert the file name.
    # The 'exit()' command will stop the script so that the other files are
    # not tested again
    # =====================================================================
    
    # in_class_test_file = "insert_the_file_name.extension"
    # evaluate_on_test_data(in_class_test_file)
    # exit()  

    # =====================================================================
    # STANDARD TEST (All files + Plotting)
    # =====================================================================
    print("Searching all test files")
    test_files = glob.glob("../data/raw/*/*test.sent_split")
    
    if not test_files:
        print("No files found in ../data/raw/.")
    else:
        print(f" {len(test_files)} test files found! Starting testing on each file\n")
        
        f1_model_list = []
        f1_nltk_list = []
        dataset_names = []
        
        for test_file in test_files:
            f1_mod, f1_nl, name = evaluate_on_test_data(test_file)
            f1_model_list.append(f1_mod * 100)
            f1_nltk_list.append(f1_nl * 100)
            
            short_name = name.split('-')[0] if '-' in name else name[:10]
            dataset_names.append(short_name)
        
        print("="*60)
        print(" TESTING COMPLETE ".center(60, "="))
        print("="*60)

        if len(dataset_names) > 1:
            print("\nGenerating plot to compare performances")
            x = np.arange(len(dataset_names))
            width = 0.35

            fig, ax = plt.subplots(figsize=(12, 6))
            rects1 = ax.bar(x - width/2, f1_model_list, width, label='XLM-RoBERTa', color='skyblue')
            rects2 = ax.bar(x + width/2, f1_nltk_list, width, label='NLTK Baseline', color='salmon')

            ax.set_ylabel('F1-Score (%)')
            ax.set_title('F1-Score comparison: XLM-RoBERTa vs NLTK')
            ax.set_xticks(x)
            ax.set_xticklabels(dataset_names, rotation=45, ha='right')
            ax.legend()
            min_score = min(min(f1_model_list), min(f1_nltk_list))
            lower_bound = max(0, min_score - 5)
            ax.set_ylim([lower_bound, 101])

            ax.bar_label(rects1, padding=3, fmt='%.2f')
            ax.bar_label(rects2, padding=3, fmt='%.2f')

            plt.tight_layout()
            plt.savefig("performance_comparison.png")
            print("Plot saved as 'performance_comparison.png' in the current directory")